#!/bin/bash
set -e

USER_BIN=$HOME/bin

# Creates user bin directory if it doesn't exist.
if [ ! -d $USER_BIN ]; then
  echo "Creating $USER_BIN directory"
  mkdir $USER_BIN 
fi

if [ ! -L $USER_BIN/lgtm ]; then
  echo "Creating symbolic link in $USER_BIN to lgtm"
  ln -s $(pwd)/lgtm $USER_BIN/lgtm
fi


if [[ :$PATH: != *:"$USER_BIN":* ]] ; then
  echo "Adding $USER_BIN to PATH"
  echo "# lgtm change. https://github.com/israel-maloney/lgtm" >> ~/.bash_profile
  echo "export PATH=$PATH:$USER_BIN" >> ~/.bash_profile
fi

if ! grep "PARANOID=" ~/.bash_profile >/dev/null 2>&1; then  
  echo "Adding lgtm paranoid mode, delete from bash_profile when you are not paranoid."
  echo "# lgtm change. https://github.com/israel-maloney/lgtm" >> ~/.bash_profile
  echo "export PARANOID=yes" >> ~/.bash_profile
fi

echo "Install is complete, last step is to source your bash_profile with:"
echo ". ~/.bash_profile"
